# Site settings
title: FaithChat
email: info@faithchat.com
description: FaithChat is dedicated to dialogue and education about God's truth to all people.

url: "https://www.faithchat.com"
baseurl: ""
permalink: /:categories/:title
#permalink: /404.html

# Organization settings
facebook_username: faithchatcom
twitter_username: faithchatcom

# Build settings
markdown: kramdown
exclude: ["Gemfile","Gemfile.lock"]
gems:
